version: "1"
services:
  web:
    build: .
    restart: always
    ports:
      - 80:80
    links:
      - db:mysql
      - cache:redis
      - es:es
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  cache:
    image: redis
    restart: always
  es:
    image: elasticsearch
    restart: always