[app]
jwt_secret = "secure"

# 定义 HTTP 监听端口
[http]
port = "80"

# 存储配置
[storage]
user = "root"
password = "root"
host = "mysql"
port = 3306
dbname = "ptr"

# redis配置
[cache]
host = "redis"
port = 6379
db = 0
password = ""

# es
[es]
url = "http://es:9200"