[app]
jwt_secret = "secure"

# 定义 HTTP 监听端口
[http]
port = "8008"

# 存储配置,使用Postgres
[storage]
user = "admin"
password = "admin"
host = "localhost"
port = 5432
dbname = "postgres"

# redis配置
[cache]
host = "localhost"
port = 6379
db = 0
password = ""

# es
[es]
url = "http://47.240.125.93:9200"